# Generated by Django 4.1.2 on 2022-10-17 10:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("items", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="item",
            name="price",
            field=models.FloatField(blank=True, null=True),
        ),
    ]
