# Generated by Django 4.1.2 on 2022-10-17 10:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("items", "0002_item_price"),
    ]

    operations = [
        migrations.AddField(
            model_name="item",
            name="url",
            field=models.TextField(blank=True),
        ),
    ]
